{"uuid": "56d03b1f-b799-42b1-a7aa-00f651a0690f", "befores": [{"name": "login_fixture", "status": "broken", "statusDetails": {"message": "NameError: name 'base_data' is not defined\n", "trace": "  File \"/Users/zhouqi/PycharmProjects/pytestDemo/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/zhouqi/PycharmProjects/pytestDemo/venv/lib/python3.8/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/zhouqi/PycharmProjects/pytestDemo/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/zhouqi/PycharmProjects/pytestDemo/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/zhouqi/PycharmProjects/pytestDemo/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/zhouqi/PycharmProjects/pytestDemo/testcases/conftest.py\", line 45, in login_fixture\n    username = base_data[\"init_admin_user\"][\"username\"]\n"}, "start": 1735623710910, "stop": 1735623710911}], "start": 1735623710910, "stop": 1735623711655}